export const data = [
    {
        name: "Washing",
        num: "01",
        badge: "Natural Fiber",
        title: "Easy Care & Long-Lasting Finish",
        text: "Our fabrics are designed for easy maintenance with strong weaving, long-lasting color quality, and everyday durability, making them suitable for regular use in apparel, upholstery, and furnishing applications.",
        image: "/images/collections/washing.jpg",
    },
    {
        name: "Affordable",
        num: "02",
        badge: "Affordable",
        title: "Premium Quality at Competitive Pricing",
        text: "We provide premium-quality fabrics at competitive export pricing, helping buyers achieve the perfect balance of quality, style, durability, and cost-effectiveness for bulk and commercial textile requirements.",
        image: "/images/collections/affordable.jpg",
    },
    {
        name: "Comfortable",
        num: "03",
        badge: "soft",
        title: "Soft Textures for Everyday Use",
        text: "Crafted using soft yarns and breathable materials, our fabrics offer superior comfort, smooth texture, and flexibility, making them ideal for garments, upholstery, and home furnishing products.",
        image: "/images/collections/comfortable.jpg",
    },
    {
        name: "Quality Material",
        num: "04",
        badge: "high quality",
        title: "Carefully Crafted with Premium Yarns",
        text: "Made with carefully selected yarns and advanced weaving techniques, our fabrics deliver excellent texture, durability, finishing, and long-term performance for global textile and furnishing markets.",
        image: "/images/collections/high-qulity.jpg",
    },
    {
        name: "Elegant Designs",
        num: "05",
        badge: "modern designs",
        title: "Timeless Patterns with Modern Appeal",
        text: "Our fabric collections feature timeless patterns, modern textures, and sophisticated finishes designed to enhance fashion, interiors, upholstery, and decorative textile applications with a premium visual appeal.",
        image: "/images/collections/elegant.jpg",
    },
];